package com.example.ui.utils

import com.example.compat.*
import kotlinx.coroutines.IO

object AppLocalization {
    private val frMap = mapOf(
        // Login & Auth
        "title" to "Connexion de l'Enseignant",
        "welcome" to "Bienvenue à nouveau ! Connectez-vous rapidement pour lier vos données, suivre et gérer les notes et les élèves de vos classes en toute sécurité.",
        "google_sign_in" to "Connexion rapide avec Google 🚀",
        "footer" to "Tous droits réservés © Développeur : El Moctar Yedaly 🇲🇷 2026",
        
        // Navigation & TopBar
        "app_title" to "Mon Application Scolaire 🏫",
        "teacher_notebook" to "Cahier de l'Enseignant",
        "select_academic_year" to "Cahier de l'enseignant - Sélectionner l'année 📅",
        "academic_year" to "Année Scolaire",
        "year" to "Année",
        "kottby_platform" to "Bibliothèque Scolaire 📚",
        "teacher_exchange" to "Échange d'Enseignants 🤝",
        "logout" to "Se déconnecter",
        "exit" to "Déconnexion",
        "back" to "Retour",
        "menu" to "Menu Principal 📌",
        "home_classes" to "Accueil & Classes 🏫",
        "tools_sync" to "Outils & Synchronisation ⚙️",
        "cloud_sync" to "Synchroniser avec le Cloud ☁️",
        "class_manager_admin" to "Gestion des Classes (Admin) 👑",
        "respected_teacher" to "Cher Enseignant",
        "system_admin" to "Administrateur Principal 👑",
        "approved_teacher" to "Enseignant Agréé 🏅",
        "app_language" to "Langue de l'application 🌐",
        
        // Grades & Selection
        "grades_entry_title" to "Saisie et gestion des notes 📝",
        "grades_entry_subtitle" to "Veuillez sélectionner le trimestre et la méthode de saisie puis la matière.",
        "select_current_term" to "Choisir le trimestre actuel 📅",
        "term_1" to "1er Trimestre ❶",
        "term_2" to "2ème Trimestre ❷",
        "term_3" to "3ème Trimestre ❸",
        "term_1_short" to "1er Trimestre",
        "term_2_short" to "2ème Trimestre",
        "term_3_short" to "3ème Trimestre",
        "annual" to "Annuel",
        "grading_method" to "Méthode de saisie des notes 🛠️",
        "grade_by_subject" to "Saisir une matière pour toute la classe",
        "grade_by_student" to "Saisir toutes les matières pour un élève",
        "select_subject_prompt" to "Sélectionner la matière à évaluer 📘",
        "select_student_prompt" to "Sélectionner l'élève à évaluer 👨‍🎓",
        "choose_subject_ph" to "Choisir la matière...",
        "choose_student_ph" to "Choisir l'élève...",
        "start_grading_btn" to "Commencer la saisie des notes 🚀",
        "back_modify_options" to "Retour aux options ↩️",
        "save_subject_grades" to "Enregistrer les notes de la matière",
        "save_student_grades" to "Enregistrer les notes de l'élève",
        
        // Dashboard & Years
        "dashboard_stats" to "Statistiques Générales 📊",
        "class_stats_title" to "Tableau de bord et statistiques de la classe 📊",
        "select_exam_for_stats" to "Sélectionner l'examen pour afficher les statistiques 🔍",
        "class_general_avg" to "Moyenne Générale de la Classe",
        "overall_pass_rate" to "Taux de Réussite Global",
        "school_census_stats" to "Statistiques de l'Effectif Scolaire 🏫",
        "total_students_count" to "Nombre total d'élèves :",
        "boys_count" to "Garçons :",
        "girls_count" to "Filles :",
        "students_unit" to "élèves",
        "boys_unit" to "garçons",
        "girls_unit" to "filles",
        "subject_comprehension_levels" to "Niveau d'assimilation et notes par matière 📚",
        "no_subjects_for_class" to "Aucune matière ajoutée pour cette classe.",
        "annual_results_progress" to "Progression de la saisie des notes annuelles 📊",
        "results_progress_subtitle" to "Suivi relatif indiquant l'avancement de la saisie des notes",
        "overall_annual_progress" to "Taux de progression annuel global",
        "grade_points_unit" to "notes",
        
        "total_students" to "Total Élèves",
        "active_classes" to "Classes Actives",
        "add_new_year" to "Ajouter une année scolaire 📅",
        "current_year" to "Année en cours",
        "available_classes" to "Classes disponibles cette année",
        "create_class" to "Créer une classe ➕",
        "no_classes_yet" to "Aucune classe ajoutée pour cette année",
        "level" to "Niveau",
        "students_count" to "Nombre d'élèves",
        "class_name" to "Nom de la classe",
        "school_name" to "Nom de l'école",
        "moughataa" to "Moughataa",
        "wilaya" to "Wilaya",
        "confirm" to "Confirmer",
        "cancel" to "Annuler",
        "save" to "Enregistrer",
        "edit" to "Modifier",
        "delete" to "Supprimer",
        "search" to "Rechercher...",
        
        // Tabs
        "tab_students" to "Élèves 👥",
        "tab_subjects" to "Matières 📚",
        "tab_grades" to "Notes & Évaluation 📝",
        "tab_reports" to "Rapports & Bulletins 📊",
        "tab_library" to "Bibliothèque 📚",
        
        // Students
        "students_list" to "Liste des élèves",
        "add_student" to "Inscrire un nouvel élève",
        "add_new_student" to "Inscrire un nouvel élève ➕",
        "edit_student" to "Modifier l'élève",
        "delete_student" to "Supprimer l'élève",
        "student_name_ar" to "Nom complet (Arabe)",
        "student_name_fr" to "Nom complet (Français)",
        "matricule" to "Numéro Matricule",
        "nni" to "Numéro National (NNI)",
        "health_notes" to "Observations de santé",
        "no_students" to "Aucun élève dans cette classe",
        "select_class_first" to "Veuillez d'abord choisir une classe 🏫",
        "select_class_first_desc" to "Sélectionnez une classe pour activer les options supplémentaires.",
        
        // Subjects
        "subjects_and_coefficients" to "Matières & Coefficients",
        "add_subject" to "Ajouter une matière",
        "subject_name" to "Nom de la matière",
        "max_points" to "Note Maximale",
        "coefficient" to "Coefficient",
        
        // Grades & Terms
        "select_subject_grade" to "Sélectionner la matière pour saisir les notes",
        "term" to "Trimestre",
        "annual_avg" to "Moyenne Annuelle",
        "exam_grade" to "Note d'examen",
        "observation" to "Observation",
        "save_all_grades" to "Enregistrer toutes les notes 💾",
        "clear_grades" to "Effacer les notes 🗑️",
        "grading_status" to "État de la saisie",
        "completed" to "Terminé",
        "incompleted" to "Incomplet",
        
        // Observations
        "obs_excellent" to "Excellent",
        "obs_very_good" to "Très Bien",
        "obs_good" to "Bien",
        "obs_fair" to "Assez Bien",
        "obs_weak" to "Insuffisant",
        
        // Reports
        "reports_title" to "Extraction des rapports et bulletins 📊",
        "reports_subtitle" to "Consultez les bulletins des élèves avec calcul de la moyenne et du rang, ou extrayez le procès-verbal détaillé.",
        "select_report_prompt" to "Sélectionner le rapport ou bulletin souhaité 📋",
        "general_class_lists" to "📋 Listes et registres généraux de la classe",
        "report_individual" to "Bulletin individuel 👤",
        "report_duo" to "Bulletins en duo (2 par page) 🖨️",
        "report_detailed" to "Procès-verbal détaillé 📊",
        "report_cards" to "Bulletins de notes",
        "class_student_list" to "Liste des élèves 👥",
        "french_registration_list" to "Inscription en Français 📝",
        "singers_list" to "Chorale / Hymne 🎤",
        "sweepers_list" to "Tour de rôle Nettoyage 🧹",
        "annual_averages_only" to "Moyennes Annuelles 📈",
        "annual_ledger" to "Registre Annuel 📜",
        "all_class_reports_title" to "Bulletins de notes de toute la classe 🖨️",
        "all_class_reports_desc" to "Générer les bulletins de tous les élèves en un seul clic. Chaque page A4 contient deux bulletins combinés avec espaces de signature.",
        "download_class_reports" to "Télécharger les bulletins de la classe 📥",
        "share_class_reports" to "Partager les bulletins de la classe 💚",
        "student_directory_title" to "Liste officielle des élèves 📋",
        "student_directory_desc" to "Générer la liste officielle des élèves classés par ordre alphabétique pour affichage ou administration.",
        "download_students_list" to "Télécharger la liste des élèves 📥",
        "share_students_list" to "Partager la liste des élèves 💚",
        "french_list_title" to "Liste des élèves en langue française 📝",
        "singers_list_title" to "Liste officielle de la chorale 🎤",
        "sweeping_list_title" to "Planning de nettoyage et d'hygiène 🧹",
        "detailed_pv_title" to "Procès-verbal détaillé du trimestre 📊",
        "annual_pv_title" to "Procès-verbal des moyennes annuelles 🏆",
        "annual_avg_summary_title" to "Liste et résumé des moyennes annuelles 📈",
        "annual_ledger_title" to "Registre annuel des procès-verbaux 📜",
        "download_list" to "Télécharger la liste 📥",
        "share_list" to "Partager la liste 💚",
        "download_pv" to "Télécharger le PV 📥",
        "share_pv" to "Partager le PV 💚",
        "download_schedule" to "Télécharger le planning 📥",
        "share_schedule" to "Partager le planning 💚",
        "download_ledger" to "Télécharger le registre 📥",
        "share_ledger" to "Partager le registre 💚",
        "select_student_individual_prompt" to "Sélectionner l'élève pour afficher et exporter son bulletin :",
        "download_student_report" to "Télécharger le bulletin 📥",
        "share_student_report" to "Partager le bulletin 💚",
        "copy_report_text" to "Copier le bulletin sous forme de texte 📋",
        "detailed_results" to "Procès-verbal détaillé des résultats",
        "annual_averages" to "Procès-verbal des moyennes annuelles",
        "download_pdf" to "Télécharger PDF",
        "share_pdf" to "Partager PDF",
        "print" to "Imprimer",
        "generating_pdf" to "Génération du fichier PDF en cours...",
        
        // Levels
        "level_af1" to "1ère Année Primaire (AF1)",
        "level_af2" to "2ème Année Primaire (AF2)",
        "level_af3" to "3ème Année Primaire (AF3)",
        "level_af4" to "4ème Année Primaire (AF4)",
        "level_af5" to "5ème Année Primaire (AF5)",
        "level_af6" to "6ème Année Primaire (AF6)",
        
        // Teacher Exchange
        "teacher_exchange_wilayas" to "Échange d'enseignants (Inter-wilayas) 🏛️",
        "teacher_exchange_moughataas" to "Échange d'enseignants (Intra-wilaya) 📍",
        "exchange_platform" to "Plateforme d'échange d'enseignants 🤝",
        "add_exchange_post" to "Publier une demande de mutation ✍️",
        "current_wilaya" to "Wilaya actuelle",
        "current_moughataa" to "Moughataa actuelle",
        "target_wilaya" to "Wilaya souhaitée",
        "target_moughataa" to "Moughataa souhaitée",
        "phone_whatsapp" to "Téléphone / WhatsApp",
        "publish" to "Publier",
        "view" to "Voir",
        "offers" to "Offres 📋",
        "create_post" to "Publier une annonce ✍️",
        "my_posts" to "Mes annonces 👤",

        // Useful links & library
        "useful_links_library" to "Liens utiles, livres et références 📖",
        "useful_links_subtitle" to "Consultez les liens utiles, livres et références disponibles pour tous les utilisateurs",
        "no_links_or_references" to "Aucun lien ni référence",
        "no_links_desc" to "Aucun lien utile ni référence n'a encore été ajouté par l'administration.",

        // Extra Dashboard & Common Elements
        "app_footer_copyright" to "Cahier de l'Enseignant - v2.5\nTous droits réservés © Développeur : El Mokhtar Yedaly 2026",
        "teacher_id_prefix" to "ID : ",
        "total_registered_students" to "Total des élèves inscrits",
        "male_count_label" to "Garçons",
        "female_count_label" to "Filles",
        "sections_count_label" to "Classes",
        "students_per_section_title" to "Nombre d'élèves par classe :",
        "no_sections_yet" to "Aucune classe pour le moment",
        "student_unit_singular" to "Élève",
        "student_unit_plural" to "Élèves",
        "select_academic_year_prompt" to "Sélectionnez l'année scolaire de travail 📅",
        "no_academic_years_yet" to "Aucune année scolaire enregistrée pour le moment",
        "no_academic_years_desc" to "Appuyez sur le bouton (+) en bas de l'écran pour créer votre première classe.",
        "academic_year_prefix" to "Année scolaire :",
        "registered_classes_suffix" to "Classes enregistrées",
        "ongoing_year_badge" to "En cours",

        // Extra Students List
        "add_new_student_btn" to "Inscrire un nouvel élève +",
        "all_students_header" to "Tous les élèves de la classe",
        "view_btn" to "Voir 👁️",
        "no_students_in_class" to "Aucun élève inscrit dans cette classe pour le moment.",

        // Extra Reports Screen
        "french_insertion_btn" to "Insertion du français 📝",
        "sweepers_btn" to "Service de balayage 🧹",
        "singers_btn" to "Chorale / Hymne 🎤",
        "class_general_list_note" to "Cette liste est générale à la classe et indépendante des trimestres ; elle est générée et partagée au début de l'année scolaire. 💡",
        "single_report_chip" to "Bulletin individuel 👤",
        "duo_report_chip" to "Bulletins doubles (2 par page) 🖨️",
        "class_print_list_title" to "Liste des élèves de la classe pour impression 📋",
        "download_students_list_btn" to "Télécharger la liste des élèves 📤",
        "share_students_list_btn" to "Partager la liste des élèves 💚",

        // Extra Statistics Screen
        "subject_avg_label" to "Moyenne de la matière :",
        "max_grade_in_class" to "Note maximale de la classe :",
        "min_grade_in_class" to "Note minimale de la classe :",
        "assimilation_level" to "Niveau d'assimilation :",
        "weak_support_needed" to "Faible ⚠️ (Besoin de soutien)",
        "fair_level" to "Moyen 🟡",
        "good_level" to "Bon 🟢",
        "excellent_level" to "Excellent ⭐",

        "inter_moughataa_exchange_title" to "Échange d'enseignants (Intra-wilaya) 📍",
        "inter_wilaya_exchange_title" to "Échange d'enseignants (Inter-wilayas) 🏛️",
        "disclaimer_exchange_responsibility" to "L'application Cahier de l'Enseignant n'est pas responsable des accords entre personnes, elle fournit uniquement la mise en relation entre enseignants.",
        "commune_label" to "Commune :",
        "school_name_label" to "Nom de l'école :",
        "workplace_label" to "Lieu de travail :",
        "wilaya_label" to "Wilaya :",
        "moughataa_label" to "Moughataa :",
        "current_moughataa_label" to "Moughataa actuelle :"
    )

    fun tr(key: String, fallback: String, lang: String): String {
        return if (lang == "fr") {
            frMap[key] ?: fallback
        } else {
            fallback
        }
    }
}
